export const data = [
    {
      Question: 'What is Redux?',
      Option1: 'Redux is State Management System',
      Option2: 'Redux is State',
      Option3: 'Redux is Data Type',
      Option4: 'Redux is a part of HTML',
    },
    {
      Question: 'What is the primary use of Redux?',
      Option1: 'To manage and centralize application state',
      Option2: 'To create CSS styles',
      Option3: 'To handle API requests',
      Option4: 'To manage HTML templates',
    },
    {
      Question: 'What are the core principles of Redux?',
      Option1: 'Single source of truth, state is read-only, changes are made with pure functions',
      Option2: 'State is shared, changes are made with impure functions',
      Option3: 'State is distributed, changes are automatic',
      Option4: 'None of the above',
    },
    {
      Question: 'What is an action in Redux?',
      Option1: 'A function to modify HTML',
      Option2: 'An object that describes what to do',
      Option3: 'A predefined API call',
      Option4: 'A CSS property',
    },
    {
      Question: 'What is a reducer in Redux?',
      Option1: 'A function that updates the state based on an action',
      Option2: 'A data storage mechanism',
      Option3: 'A tool to handle CSS styles',
      Option4: 'A middleware component',
    },
    {
      Question: 'What is the store in Redux?',
      Option1: 'A centralized place to hold the application state',
      Option2: 'A JavaScript library',
      Option3: 'An API request manager',
      Option4: 'A tool for debugging',
    },
    {
      Question: 'How does Redux achieve immutability?',
      Option1: 'By using pure functions in reducers',
      Option2: 'By directly modifying the state',
      Option3: 'By using HTML templates',
      Option4: 'By adding middleware',
    },
    {
      Question: 'What middleware is commonly used with Redux?',
      Option1: 'Redux Thunk',
      Option2: 'Redux Toolkit',
      Option3: 'Node.js',
      Option4: 'React Router',
    },
    {
      Question: 'What is Redux Toolkit?',
      Option1: 'A library for simplifying Redux development',
      Option2: 'A CSS framework',
      Option3: 'A JavaScript language feature',
      Option4: 'A tool for managing HTML templates',
    },
    {
      Question: 'Which method is used to dispatch an action in Redux?',
      Option1: 'dispatch()',
      Option2: 'sendAction()',
      Option3: 'triggerAction()',
      Option4: 'perform()',
    },
  ];
  